"""add company table

Revision ID: 21d0fb45791a
Revises: 6629395232d0
Create Date: 2026-07-04 08:04:15.596118
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '21d0fb45791a'
down_revision: str | None = '6629395232d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.add_column('deals', sa.Column('seller_company_id', sa.Integer(), nullable=False))
    op.add_column('deals', sa.Column('buyer_company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deals', 'companies', ['buyer_company_id'], ['id'])
    op.create_foreign_key(None, 'deals', 'companies', ['seller_company_id'], ['id'])
    op.drop_column('deals', 'buyer_company')
    op.drop_column('deals', 'seller_company')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.add_column('deals', sa.Column('seller_company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('buyer_company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'buyer_company_id')
    op.drop_column('deals', 'seller_company_id')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
