"""add company to user

Revision ID: 6629395232d0
Revises: 202607030003
Create Date: 2026-07-04 07:33:24.711776
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6629395232d0'
down_revision: str | None = '202607030003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
