"""add_risk_rules_table

Revision ID: 78b50eadac3b
Revises: 21d0fb45791a
Create Date: 2026-07-04 09:20:57.678999
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '78b50eadac3b'
down_revision: str | None = '21d0fb45791a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('invert', sa.Boolean(), nullable=False),
    sa.Column('document_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rules_deal_id'), 'risk_rules', ['deal_id'], unique=False)
    op.create_index(op.f('ix_risk_rules_id'), 'risk_rules', ['id'], unique=False)
    op.create_index(op.f('ix_risk_rules_rule_key'), 'risk_rules', ['rule_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_rules_rule_key'), table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_id'), table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_deal_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
